# Generated by Django 4.2.2 on 2023-10-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_Order',
            new_name='date_order',
        ),
    ]
